apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: books
spec:
  replicas: 1
  selector:
    matchLabels: { app: api }
  template:
    metadata:
      labels: { app: api }
    spec:
      containers:
        - name: api
          image: books-api:dev
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: api-config
            - secretRef:
                name: db-secret
          livenessProbe:
            httpGet: { path: /health, port: 3001 }
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet: { path: /health, port: 3001 }
            initialDelaySeconds: 2
            periodSeconds: 5